ifeq (${MINGW},1)
CXX=i686-pc-mingw32-g++
FLTK=/usr/local/cross-tools/i386-mingw32/bin/fltk-config
EXE=.exe
else
FLTK=fltk-config
endif

CXXFLAGS = `${FLTK} --use-images --cxxflags`
LIBS = `${FLTK} --use-images --ldflags`
CPPFILES = src/checkers.cc \
	src/rcheckers.cc\
	src/echeckers.cc\
	src/flcheckers.cc

#	src/pdn.cc\


OBJ   = $(CPPFILES:.cc=.o)

all: flchekers${EXE}


flchekers${EXE}: $(OBJ) 
	$(CXX) -o $@ $^ $(LIBS) $(CXXFLAGS) 

