/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */

#ifdef _LIBC
 #error Applications may not define the macro _LIBC
#endif

#define __stub_chflags
#define __stub_chflags
#define __stub_fattach
#define __stub_fattach
#define __stub_fchflags
#define __stub_fchflags
#define __stub_fdetach
#define __stub_fdetach
#define __stub_fegetexceptflag
#define __stub_fegetexceptflag
#define __stub_feupdateenv
#define __stub_feupdateenv
#define __stub_fgetxattr
#define __stub_fgetxattr
#define __stub_flistxattr
#define __stub_flistxattr
#define __stub_fremovexattr
#define __stub_fremovexattr
#define __stub_fsetxattr
#define __stub_fsetxattr
#define __stub_futimes
#define __stub_futimes
#define __stub_getcontext
#define __stub_getcontext
#define __stub_getmsg
#define __stub_getmsg
#define __stub_getpmsg
#define __stub_getpmsg
#define __stub_getxattr
#define __stub_getxattr
#define __stub_gtty
#define __stub_gtty
#define __stub_lchmod
#define __stub_lchmod
#define __stub_lgetxattr
#define __stub_lgetxattr
#define __stub_listxattr
#define __stub_listxattr
#define __stub_llistxattr
#define __stub_llistxattr
#define __stub_lremovexattr
#define __stub_lremovexattr
#define __stub_lsetxattr
#define __stub_lsetxattr
#define __stub_lutimes
#define __stub_lutimes
#define __stub_makecontext
#define __stub_makecontext
#define __stub_posix_fadvise64
#define __stub_posix_fadvise64
#define __stub_putmsg
#define __stub_putmsg
#define __stub_putpmsg
#define __stub_putpmsg
#define __stub_removexattr
#define __stub_removexattr
#define __stub_revoke
#define __stub_revoke
#define __stub_sched_getaffinity
#define __stub_sched_getaffinity
#define __stub_sched_setaffinity
#define __stub_sched_setaffinity
#define __stub_sendfile64
#define __stub_sendfile64
#define __stub_setcontext
#define __stub_setcontext
#define __stub_setlogin
#define __stub_setlogin
#define __stub_setxattr
#define __stub_setxattr
#define __stub_sigreturn
#define __stub_sigreturn
#define __stub_sstk
#define __stub_sstk
#define __stub_stty
#define __stub_stty
#define __stub_swapcontext
#define __stub_swapcontext
